name: Node CI

on: [push]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        node-version: [8.x, 10.x, 12.x]
        python-version: [3.6, 3.7, 3.8]  # 2.7, 3.5,
        platform: 
          - { os: windows-latest, hunspell: true }
          - { os: windows-latest }
          - { os: macos-latest, hunspell: true }  
          - { os: macos-latest }  
          - { os: ubuntu-latest }

    runs-on: ${{ matrix.platform.os }}

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: npm install, build, and test
      run: |
        npm install
        npm test
    - name: node-gyp install
      run: |
        npm install -g node-gyp
    - name: node-gyp configure
      run: |
        node-gyp configure
        node-gyp build
      env:
        SPELLCHECKER_PREFER_HUNSPELL: ${{ matrix.platform.hunspell }}
